ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt install -y gdb

COPY src /src

RUN mkdir -p /src/build && cd /src/build && \
    cmake .. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_STANDARD=20 && \
    make -j8

CMD ["gdb", "/src/build/server/server"]
