# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seqr_query_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seqr_query_service.proto',
  package='seqr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18seqr_query_service.proto\x12\x04seqr\"\xd1\x02\n\nExpression\x12\x10\n\x06\x63olumn\x18\x01 \x01(\tH\x00\x12+\n\x07literal\x18\x02 \x01(\x0b\x32\x18.seqr.Expression.LiteralH\x00\x12%\n\x04\x63\x61ll\x18\x03 \x01(\x0b\x32\x15.seqr.Expression.CallH\x00\x1a\x90\x01\n\x07Literal\x12\x12\n\x08\x62ool_val\x18\x01 \x01(\x08H\x00\x12\x13\n\tint32_val\x18\x02 \x01(\x05H\x00\x12\x13\n\tint64_val\x18\x03 \x01(\x03H\x00\x12\x13\n\tfloat_val\x18\x04 \x01(\x02H\x00\x12\x14\n\ndouble_val\x18\x05 \x01(\x01H\x00\x12\x14\n\nstring_val\x18\x06 \x01(\tH\x00\x42\x06\n\x04type\x1a\x42\n\x04\x43\x61ll\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12#\n\targuments\x18\x02 \x03(\x0b\x32\x10.seqr.ExpressionB\x06\n\x04type\"\xca\x01\n\x0cQueryRequest\x12\x12\n\narrow_urls\x18\x01 \x03(\t\x12\x1a\n\x12projection_columns\x18\x02 \x03(\t\x12+\n\x11\x66ilter_expression\x18\x03 \x01(\x0b\x32\x10.seqr.Expression\x12\x14\n\x0csort_columns\x18\x04 \x03(\t\x12\x16\n\x0esort_ascending\x18\x05 \x01(\x08\x12\x13\n\x0bmax_results\x18\x06 \x01(\x05\x12\x1a\n\x12\x66irst_result_index\x18\x07 \x01(\x05\"$\n\rQueryResponse\x12\x13\n\x0bnum_results\x18\x01 \x01(\x05\x32\x42\n\x0cQueryService\x12\x32\n\x05Query\x12\x12.seqr.QueryRequest\x1a\x13.seqr.QueryResponse\"\x00\x62\x06proto3'
)




_EXPRESSION_LITERAL = _descriptor.Descriptor(
  name='Literal',
  full_name='seqr.Expression.Literal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_val', full_name='seqr.Expression.Literal.bool_val', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32_val', full_name='seqr.Expression.Literal.int32_val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int64_val', full_name='seqr.Expression.Literal.int64_val', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='seqr.Expression.Literal.float_val', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_val', full_name='seqr.Expression.Literal.double_val', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='seqr.Expression.Literal.string_val', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='seqr.Expression.Literal.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=152,
  serialized_end=296,
)

_EXPRESSION_CALL = _descriptor.Descriptor(
  name='Call',
  full_name='seqr.Expression.Call',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_name', full_name='seqr.Expression.Call.function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='seqr.Expression.Call.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=364,
)

_EXPRESSION = _descriptor.Descriptor(
  name='Expression',
  full_name='seqr.Expression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='seqr.Expression.column', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='literal', full_name='seqr.Expression.literal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='call', full_name='seqr.Expression.call', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EXPRESSION_LITERAL, _EXPRESSION_CALL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='seqr.Expression.type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=372,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='seqr.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrow_urls', full_name='seqr.QueryRequest.arrow_urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projection_columns', full_name='seqr.QueryRequest.projection_columns', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_expression', full_name='seqr.QueryRequest.filter_expression', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sort_columns', full_name='seqr.QueryRequest.sort_columns', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sort_ascending', full_name='seqr.QueryRequest.sort_ascending', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='seqr.QueryRequest.max_results', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_result_index', full_name='seqr.QueryRequest.first_result_index', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=577,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='seqr.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_results', full_name='seqr.QueryResponse.num_results', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=615,
)

_EXPRESSION_LITERAL.containing_type = _EXPRESSION
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['bool_val'])
_EXPRESSION_LITERAL.fields_by_name['bool_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['int32_val'])
_EXPRESSION_LITERAL.fields_by_name['int32_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['int64_val'])
_EXPRESSION_LITERAL.fields_by_name['int64_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['float_val'])
_EXPRESSION_LITERAL.fields_by_name['float_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['double_val'])
_EXPRESSION_LITERAL.fields_by_name['double_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_LITERAL.oneofs_by_name['type'].fields.append(
  _EXPRESSION_LITERAL.fields_by_name['string_val'])
_EXPRESSION_LITERAL.fields_by_name['string_val'].containing_oneof = _EXPRESSION_LITERAL.oneofs_by_name['type']
_EXPRESSION_CALL.fields_by_name['arguments'].message_type = _EXPRESSION
_EXPRESSION_CALL.containing_type = _EXPRESSION
_EXPRESSION.fields_by_name['literal'].message_type = _EXPRESSION_LITERAL
_EXPRESSION.fields_by_name['call'].message_type = _EXPRESSION_CALL
_EXPRESSION.oneofs_by_name['type'].fields.append(
  _EXPRESSION.fields_by_name['column'])
_EXPRESSION.fields_by_name['column'].containing_oneof = _EXPRESSION.oneofs_by_name['type']
_EXPRESSION.oneofs_by_name['type'].fields.append(
  _EXPRESSION.fields_by_name['literal'])
_EXPRESSION.fields_by_name['literal'].containing_oneof = _EXPRESSION.oneofs_by_name['type']
_EXPRESSION.oneofs_by_name['type'].fields.append(
  _EXPRESSION.fields_by_name['call'])
_EXPRESSION.fields_by_name['call'].containing_oneof = _EXPRESSION.oneofs_by_name['type']
_QUERYREQUEST.fields_by_name['filter_expression'].message_type = _EXPRESSION
DESCRIPTOR.message_types_by_name['Expression'] = _EXPRESSION
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Expression = _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), {

  'Literal' : _reflection.GeneratedProtocolMessageType('Literal', (_message.Message,), {
    'DESCRIPTOR' : _EXPRESSION_LITERAL,
    '__module__' : 'seqr_query_service_pb2'
    # @@protoc_insertion_point(class_scope:seqr.Expression.Literal)
    })
  ,

  'Call' : _reflection.GeneratedProtocolMessageType('Call', (_message.Message,), {
    'DESCRIPTOR' : _EXPRESSION_CALL,
    '__module__' : 'seqr_query_service_pb2'
    # @@protoc_insertion_point(class_scope:seqr.Expression.Call)
    })
  ,
  'DESCRIPTOR' : _EXPRESSION,
  '__module__' : 'seqr_query_service_pb2'
  # @@protoc_insertion_point(class_scope:seqr.Expression)
  })
_sym_db.RegisterMessage(Expression)
_sym_db.RegisterMessage(Expression.Literal)
_sym_db.RegisterMessage(Expression.Call)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'seqr_query_service_pb2'
  # @@protoc_insertion_point(class_scope:seqr.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'seqr_query_service_pb2'
  # @@protoc_insertion_point(class_scope:seqr.QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)



_QUERYSERVICE = _descriptor.ServiceDescriptor(
  name='QueryService',
  full_name='seqr.QueryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=617,
  serialized_end=683,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='seqr.QueryService.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYSERVICE)

DESCRIPTOR.services_by_name['QueryService'] = _QUERYSERVICE

# @@protoc_insertion_point(module_scope)
